### ISSUE TITLE
Menu Navigation

### ISSUE THREAD

**Issue by juanferrer** [JuanFerrer/Pool#1]
- [x] Main menu
- [ ] Pause and play windows
- [ ] Interactions between them

Main menu should be first screen to be loaded. When start is clicked (and all has been set), Main menu instantiates the `GameManager` prefab and calls `StartGame()`,  passing the settings as parameters. See #5.

**Comment by juanferrer** [comment]
Pause menu? Settings? Is it happening?

**Comment by JAlsworth23** [comment]
Pause Menu I should be able to do for certain by the end of tomorrow, Settings will be trickier but I'll try my best.
